baseURL = "https://aldoiu.ro/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Mihai Aldoiu | LinkTree"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Mihai Aldoiu"
  headline = "AWS Certified Solutions Architect | Site Reliability Engineer | CKA"
  ## image = "img/author.jpg"  # path relative to static directory

  links = [
    { linkedin = "https://linkedin.com/in/aldoiu" },
    { link = { href = "https://www.credly.com/users/mihai-aldoiu/badges", text = "Certifications" } },
    { github = "https://github.com/mihaialdoiu" },
    { stack-overflow = "https://stackoverflow.com/users/18233221/mihai-a" },
    { instagram = "https://www.instagram.com/mihai.aldoiu/" }, 
    { link = { href = "https://www.shutterstock.com/g/maldoiu", text = "ShutterStock" } }
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
